In [25]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [26]:
model=load_model('model.h5')
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('onehot_encoder_Geo.pkl','rb') as file:
    onehot_encoder_Geo = pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)


In [27]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000

}

In [28]:
geo_encoded=onehot_encoder_Geo.transform([[input_data['Geography']]])
geo_encoded

c:\my development\Artificial intelligence\ANN clasification\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [29]:
gender_encoded=label_encoder_gender.transform([input_data['Gender']])

In [30]:
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_Geo.get_feature_names_out(['Geography']))

In [31]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [32]:
gender_encoded_df = pd.DataFrame({'Gender':gender_encoded})
gender_encoded_df


Gender
0       1

In [33]:
input_df = pd.DataFrame([input_data])

In [34]:
input_df['Gender']

0    Male
Name: Gender, dtype: object

In [35]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [36]:
input_df

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [37]:
input_df = pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis = 1)

In [38]:
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [40]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [41]:
prediction =model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step


array([[0.0648037]], dtype=float32)

In [42]:
prediction_prob = prediction[0][0]

In [43]:
prediction_prob

0.064803705

In [44]:
if prediction_prob>0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likey to churn")



The customer is not likey to churn
